### ISSUE TITLE
Attempting to close an open snippets dialog during long analysis hangs UI

### ISSUE THREAD

**Issue by galenbwill** [Vector35/snippets#13]
If the snippets dialog is opened while a long analysis is in progress, attempting to close the dialog hangs the entire UI.

On macOS, this actually makes it impossible to switch to another application and have it show its window on top of the frozen snippets dialog.

Not sure if this unfreezes when the analysis completes, as I've always forced binary ninja to quit when this happens.

As an aside, it would be nice if the snippets dialog weren't modal, but that probably relates to issue https://github.com/Vector35/snippets/issues/10

**Comment by psifertex** [comment]
Making the window non-model fixes it somewhat -- BN UI can still hang (#4) but you can switch just fine.
