### ISSUE TITLE
ship collection of default snippets

### ISSUE THREAD

**Issue by psifertex** [Vector35/snippets#22]

**Comment by galenbwill** [comment]
now i'm curious what a list of those default snippets might be

**Comment by psifertex** [comment]
https://gist.github.com/psifertex/6fbc7532f536775194edd26290892ef7
most likely

**Comment by psifertex** [comment]
Been curating them for a while

**Comment by psifertex** [comment]
This is done -- a downloader of examples is shipped by default.
