### ISSUE TITLE
Punctuation Color Tweaks

### ISSUE THREAD

**Issue by toolCHAINZ** [Vector35/snippets#25]
I noticed a couple odd color selections, while using the snippets plugin:
* Punctuation uses `LinearDisassemblySeparatorColor`
* The background seems to be `backgroundHighlightDarkColor` (correct me if I'm wrong; I'm not good at QT)

While this usually works well, these colors aren't *necessarily* related to another and might not have a lot of contrast, depending on the theme. 

I propose to:
* Change punctuation to `uncertainColor` since that shouldn't draw the eye too much, but should still be visible
* Change the background to `graphBackgroundDarkColor` or `linearDisassemblyBlockColor`, since every other color that's used in the snippet highlighting should be chosen by the theme to stand out against either of these.

**Comment by psifertex** [comment]
Yeah, I think Blue Steel shows it off best. I'll go ahead and make the change, thanks for looking into this!

**Comment by psifertex** [comment]
Resolved in release 1.4
