### ISSUE TITLE
Update Analysis checkbox functionality broken

### ISSUE THREAD

**Issue by PapaZetier** [Vector35/snippets#26]
AttributeError: 'SnippetTask' object has no attribute 'updateAnalysis' is raised in SnippetTask.run().

**Comment by psifertex** [comment]
Sorry for the delay in responding -- can you give me a bit more information about your setup? I can't reproduce this with version 1.17 of the plugin on MacOS or Linux in testing.

**Comment by psifertex** [comment]
pretty sure this got resolved feel free to reopen if not
