### ISSUE TITLE
Fast way to copy path

### ISSUE THREAD

**Issue by jonpalmisc** [Vector35/snippets#41]
It would be nice if there were a fast way to copy a snippet's path so that it may be opened in an editor like Vim.

**Comment by psifertex** [comment]
There's already an "open in editor" button. If you set your OS associations correctly that should do it for you.

**Comment by psifertex** [comment]
That said, it's like two lines, so... done. 😉 I added it to the context menu in the file picker so you can do it for one that isn't even open. Not going to do a new release yet as I'm also working on some improvements to auto-run on external save I'd like to land in the next release but you can clone it manually in the meantime.
